server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/goldexchange
    username: youruser
    password: yourpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

kafka:
  bootstrap-servers: localhost:9092
