apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-service
  namespace: gold-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-service
  template:
    metadata:
      labels:
        app: trade-service
    spec:
      containers:
        - name: trade-service
          image: trade-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
