apiVersion: v1
kind: Service
metadata:
  name: trade-service
  namespace: gold-exchange
spec:
  selector:
    app: trade-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
