version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
  wallet-service:
    build: ./wallet-service
    ports:
      - "8082:8082"
  trade-service:
    build: ./trade-service
    ports:
      - "8083:8083"
networks:
  default:
    driver: bridge
