apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: gold-exchange
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-int
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-ext
      protocol: TCP
      port: 29092
      targetPort: 29092
  type: ClusterIP
