apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matching-engine
  namespace: gold-exchange
spec:
  serviceName: matching-engine
  replicas: 1
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
        - name: matching-engine
          image: matching-engine
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
