apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-engine
  namespace: gold-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
        - name: matching-engine
          image: matchingengine:latest
          env:
            - name: KAFKA_BROKER
              value: kafka:9092
          ports:
            - containerPort: 8080
