apiVersion: v1
kind: Service
metadata:
  name: matching-engine
  namespace: gold-exchange
spec:
  selector:
    app: matching-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
