apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: gold-exchange
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
