apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: gold-exchange
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
