apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: gold-exchange
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
